export default interface ReadonlyDate {
    getDate(): number
    getDay(): number
    getFullYear(): number
    getHours(): number
    getMilliseconds(): number
    getMinutes(): number
    getMonth(): number
    getSeconds(): number
    getTime(): number
    getTimezoneOffset(): number
    getUTCDate(): number
    getUTCDay(): number
    getUTCFullYear(): number
    getUTCHours(): number
    getUTCMilliseconds(): number
    getUTCMinutes(): number
    getUTCMonth(): number
    getUTCSeconds(): number
    toDateString(): string
    toISOString(): string
    toJSON(): string
    toLocaleDateString(): string
    toLocaleString(): string
    toLocaleTimeString(): string
    toString(): string
    toTimeString(): string
    toUTCString(): string
    valueOf(): number
}