poms:
  mc:
    server:
      address: localhost

      status:
        cache-for: 10s

      rcon:
         port: 25575

      plugin:
        port: 24980

spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true