poms:
    database:
        port: 3306

spring:
    datasource:
        url: jdbc:mysql://${poms.database.host}:${poms.database.port}/${poms.database.name}?createDatabaseIfNotExist=true&autoReconnect=true
        username: ${poms.database.username}
        password: ${poms.database.password}
        driverClassName: com.mysql.cj.jdbc.Driver

    jpa:
        spring:
            jpa:
                database-platform: org.hibernate.dialect.MySQL8Dialect

        hibernate:
            ddl-auto: update
