poms:
    database:
        host: localhost
        port: 0

        name: poms

        username: root
        password:

spring:
    application:
        name: POMS

    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
        banner-mode: off

    profiles:
        default: development

    web:
        resources:
            add-mappings: false

    jpa:
        open-in-view: false

        hibernate:
            naming:
                implicit-strategy: ru.fominmv.poms.server.util.hibernate.CustomImplicitNamingStrategy

        properties:
            hibernate:
                globally_quoted_identifiers: true

server:
    servlet:
        context-path: /api

        session:
            cookie:
                http-only: true
                secure: true
                same-site: Lax
                name: session-id

    error:
        whitelabel:
            enabled: false
