package ru.fominmv.poms.server.security.consts

object Operation {
    const val CAN_CREATE_USERS = "CAN_CREATE_USERS"
    const val CAN_READ_USERS = "CAN_READ_USERS"
    const val CAN_UPDATE_USERS = "CAN_UPDATE_USERS"
    const val CAN_DELETE_USERS = "CAN_DELETE_USERS"

    const val CAN_CREATE_INVITES = "CAN_CREATE_INVITES"
    const val CAN_READ_INVITES = "CAN_READ_INVITES"
    const val CAN_UPDATE_INVITES = "CAN_UPDATE_INVITES"
    const val CAN_DELETE_INVITES = "CAN_DELETE_INVITES"

    const val CAN_CREATE_SERVERS = "CAN_CREATE_SERVERS"
    const val CAN_READ_SERVERS = "CAN_READ_SERVERS"
    const val CAN_UPDATE_SERVERS = "CAN_UPDATE_SERVERS"
    const val CAN_DELETE_SERVERS = "CAN_DELETE_SERVERS"

    const val CAN_MANAGE_RIGHTS = "CAN_MANAGE_RIGHTS"
}
