export const DEFAULT_APPEARING_MESSAGE_TICK        = 80
export const DEFAULT_APPEARING_MESSAGE_DELAY       = 500
export const DEFAULT_APPEARING_MESSAGE_CURSOR      = "_"
export const DEFUALT_APPEARING_MESSAGE_CURSOR_TICK = 500