export type TypeOfResult = "undefined"
                         | "bigint"
                         | "object"
                         | "boolean"
                         | "number"
                         | "string"
                         | "symbol"
                         | "function"
                         | "object"